server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/t?serverTimezone=UTC
    username: zc
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  data:
    mongodb:
      uri:  mongodb://admin:123456@localhost:27017/whTitle

  #mybatis:
  #mapper-locations: classpath:mapper/*.xml
  # type-aliases-package: com.qyq.pojo
